name: solarium_examples
description: SolariumVR examples
version: 0.0.1
#homepage: https://www.example.com
#author: Michael <email@example.com>
packages_dir: true
environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  barback: ^0.15.2
  build: ^0.9.0
  build_barback: ^0.2.0
  solarium_mason:

dependencies_overrides:
  solarium_mason:
    path: ../../mason

dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.4.0

transformer:
  - untitled